/* eslint-disable react-refresh/only-export-components -- Formatting helpers and shared UI live together. */
import { useId, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from 'react';
import { ArrowLeft, PawPrint } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ApiError, errorText, fieldErrors } from '../api/client';
import type { Booking, BookingStatus, Page } from '../api/types';

export const money = (value: number | null | undefined) => value == null ? '—' : new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value);
export const dateTime = (value: string | null | undefined) => value ? new Intl.DateTimeFormat('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh', dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—';
export const dateOnly = (value: string | null | undefined) => value ? new Intl.DateTimeFormat('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh', dateStyle: 'short' }).format(new Date(value)) : '—';
export const bookingLabel: Record<BookingStatus, string> = { PENDING: 'Chờ duyệt', CONFIRMED: 'Đã xác nhận', COMPLETED: 'Hoàn thành', CANCELLED: 'Đã hủy' };
export const bookingPrice = (booking: Booking) => booking.status === 'COMPLETED' ? booking.finalTotal : booking.estimatedTotal;
export const firstService = (booking: Booking) => booking.services?.[0]?.service?.serviceName || 'Dịch vụ';
export const vietnameseBookingDate = (local: string) => `${local}:00+07:00`;
export const fieldError = (error: unknown, field: string) => fieldErrors(error)[field];

export function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <div className={`bg-surface border border-border-custom rounded-panel p-4 sm:p-5 ${className}`}>{children}</div>; }
export function Title({ children, action }: { children: ReactNode; action?: ReactNode }) { return <div className="flex flex-wrap items-center justify-between gap-3 mb-6"><h1 className="text-2xl md:text-[28px] leading-tight font-semibold">{children}</h1>{action}</div>; }
export function Button({ children, disabled, type = 'button', onClick, variant = 'primary' }: { children: ReactNode; disabled?: boolean; type?: 'button' | 'submit'; onClick?: () => void; variant?: 'primary' | 'secondary' | 'danger' }) { return <button type={type} disabled={disabled} onClick={onClick} className={`min-h-10 px-4 py-2 rounded-control border font-semibold text-sm disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer transition-colors ${variant === 'primary' ? 'bg-plum-noir border-plum-noir text-white hover:bg-plum-light' : variant === 'danger' ? 'bg-surface border-red-700 text-red-800 hover:bg-red-50' : 'bg-surface border-border-custom text-plum-noir hover:bg-muted-surface'}`}>{children}</button>; }
const controlClass = 'w-full min-h-10 border border-border-custom rounded-control bg-surface px-3 py-2 text-base font-normal text-text-primary outline-none transition-colors focus:border-plum-noir focus-visible:ring-2 focus-visible:ring-muted-accent/40 disabled:bg-muted-surface disabled:text-text-secondary';
export function Input({ label, error, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string }) { const id = useId(); const errorId = `${id}-error`; return <label htmlFor={id} className="block text-sm font-medium space-y-1.5 min-w-0"><span className="block">{label}</span><input {...props} id={id} aria-invalid={!!error} aria-describedby={error ? errorId : props['aria-describedby']} className={controlClass} />{error && <span id={errorId} className="block text-red-800 text-sm">{error}</span>}</label>; }
export function TextArea({ label, error, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement> & { label: string; error?: string }) { const id = useId(); const errorId = `${id}-error`; return <label htmlFor={id} className="block text-sm font-medium space-y-1.5 min-w-0"><span className="block">{label}</span><textarea {...props} id={id} aria-invalid={!!error} aria-describedby={error ? errorId : props['aria-describedby']} className={`${controlClass} min-h-24`} />{error && <span id={errorId} className="block text-red-800 text-sm">{error}</span>}</label>; }
export function Select({ label, options, error, ...props }: SelectHTMLAttributes<HTMLSelectElement> & { label: string; options: { value: string; label: string }[]; error?: string }) { const id = useId(); const errorId = `${id}-error`; const current = typeof props.value === 'string' ? props.value : ''; return <label htmlFor={id} className="block text-sm font-medium space-y-1.5 min-w-0"><span className="block">{label}</span><select {...props} id={id} aria-invalid={!!error} aria-describedby={error ? errorId : props['aria-describedby']} className={controlClass}>{current && !options.some(option => option.value === current) && <option value={current}>Đã chọn #{current}</option>}{options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select>{error && <span id={errorId} className="block text-red-800 text-sm">{error}</span>}</label>; }
export function Notice({ error, success }: { error?: unknown; success?: string }) { return <>{error && <div role="alert" className="rounded-control border border-red-200 bg-red-50 text-red-900 px-4 py-3 text-sm mb-4">{errorText(error)}</div>}{success && <div role="status" className="rounded-control border border-emerald-200 bg-emerald-50 text-emerald-900 px-4 py-3 text-sm mb-4">{success}</div>}</>; }
export function QueryState({ loading, error, retry, children }: { loading: boolean; error?: unknown; retry?: () => void; children: ReactNode }) { if (loading) return <div role="status" className="border-y border-border-custom py-5 text-text-secondary">Đang tải dữ liệu…</div>; if (error) return <div className="border-y border-border-custom py-5"><Notice error={error} />{retry && <Button onClick={retry}>Thử lại</Button>}</div>; return <>{children}</>; }
export function Pager<T>({ page, setPage, data }: { page: number; setPage: (page: number) => void; data?: Page<T> }) { if (!data || data.total <= data.limit) return null; return <nav aria-label="Phân trang" className="flex flex-wrap items-center gap-3 mt-5"><Button variant="secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>Trước</Button><span className="text-sm text-text-secondary">Trang {page} / {Math.ceil(data.total / data.limit)}</span><Button variant="secondary" disabled={page * data.limit >= data.total} onClick={() => setPage(page + 1)}>Tiếp</Button></nav>; }
export function Empty({ children }: { children: ReactNode }) { return <div className="border-y border-border-custom py-8 text-center text-text-secondary"><PawPrint aria-hidden="true" size={22} className="mx-auto mb-2 text-muted-accent" /><p>{children}</p></div>; }
export function Back({ to, children = 'Quay lại' }: { to: string; children?: ReactNode }) { return <Link className="inline-flex items-center gap-1 text-sm text-plum-noir underline underline-offset-4 mb-3" to={to}><ArrowLeft aria-hidden="true" size={16} />{children}</Link>; }
export function statusError(error: unknown) { return error instanceof ApiError ? error.status : 0; }
