/* eslint-disable react-refresh/only-export-components -- Formatting helpers and shared UI live together. */
import type { InputHTMLAttributes, ReactNode, SelectHTMLAttributes, TextareaHTMLAttributes } from 'react';
import { Link } from 'react-router-dom';
import { ApiError, errorText, fieldErrors } from '../api/client';
import type { Booking, BookingStatus, Page } from '../api/types';

export const money = (value: number | null | undefined) => value == null ? '—' : new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value);
export const dateTime = (value: string | null | undefined) => value ? new Intl.DateTimeFormat('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh', dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—';
export const dateOnly = (value: string | null | undefined) => value ? new Intl.DateTimeFormat('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh', dateStyle: 'short' }).format(new Date(value)) : '—';
export const bookingLabel: Record<BookingStatus, string> = { PENDING: 'Chờ duyệt', CONFIRMED: 'Đã xác nhận', COMPLETED: 'Hoàn thành', CANCELLED: 'Đã hủy' };
export const bookingPrice = (booking: Booking) => booking.status === 'COMPLETED' ? booking.finalTotal : booking.estimatedTotal;
export const firstService = (booking: Booking) => booking.services?.[0]?.service?.serviceName || 'Dịch vụ';
export const vietnameseBookingDate = (local: string) => `${local}:00+07:00`;
export const fieldError = (error: unknown, field: string) => fieldErrors(error)[field];

export function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <div className={`bg-surface border border-border-custom rounded-xl p-5 ${className}`}>{children}</div>; }
export function Title({ children, action }: { children: ReactNode; action?: ReactNode }) { return <div className="flex flex-wrap items-center justify-between gap-3 mb-6"><h1 className="text-3xl font-bold">{children}</h1>{action}</div>; }
export function Button({ children, disabled, type = 'button', onClick, variant = 'primary' }: { children: ReactNode; disabled?: boolean; type?: 'button' | 'submit'; onClick?: () => void; variant?: 'primary' | 'secondary' | 'danger' }) { return <button type={type} disabled={disabled} onClick={onClick} className={`px-4 py-2 rounded-lg font-semibold text-sm disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer ${variant === 'primary' ? 'bg-plum-noir text-white hover:bg-plum-light' : variant === 'danger' ? 'bg-red-700 text-white hover:bg-red-800' : 'bg-muted-surface text-plum-noir hover:bg-border-custom'}`}>{children}</button>; }
export function Input({ label, error, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string }) { return <label className="block text-sm font-medium space-y-1"><span>{label}</span><input {...props} className="w-full border border-border-custom rounded-lg bg-white px-3 py-2 font-normal outline-none focus:border-plum-noir" />{error && <span className="block text-red-700 text-xs">{error}</span>}</label>; }
export function TextArea({ label, error, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement> & { label: string; error?: string }) { return <label className="block text-sm font-medium space-y-1"><span>{label}</span><textarea {...props} className="w-full border border-border-custom rounded-lg bg-white px-3 py-2 font-normal outline-none focus:border-plum-noir" />{error && <span className="block text-red-700 text-xs">{error}</span>}</label>; }
export function Select({ label, options, error, ...props }: SelectHTMLAttributes<HTMLSelectElement> & { label: string; options: { value: string; label: string }[]; error?: string }) { const current = typeof props.value === 'string' ? props.value : ''; return <label className="block text-sm font-medium space-y-1"><span>{label}</span><select {...props} className="w-full border border-border-custom rounded-lg bg-white px-3 py-2 font-normal outline-none focus:border-plum-noir">{current && !options.some(option => option.value === current) && <option value={current}>Đã chọn #{current}</option>}{options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select>{error && <span className="block text-red-700 text-xs">{error}</span>}</label>; }
export function Notice({ error, success }: { error?: unknown; success?: string }) { return <>{error && <div role="alert" className="rounded-lg bg-red-50 text-red-800 px-4 py-3 text-sm mb-4">{errorText(error)}</div>}{success && <div role="status" className="rounded-lg bg-green-50 text-green-800 px-4 py-3 text-sm mb-4">{success}</div>}</>; }
export function QueryState({ loading, error, retry, children }: { loading: boolean; error?: unknown; retry?: () => void; children: ReactNode }) { if (loading) return <p role="status">Đang tải dữ liệu…</p>; if (error) return <Card><Notice error={error} />{retry && <Button onClick={retry}>Thử lại</Button>}</Card>; return <>{children}</>; }
export function Pager<T>({ page, setPage, data }: { page: number; setPage: (page: number) => void; data?: Page<T> }) { if (!data || data.total <= data.limit) return null; return <div className="flex items-center gap-3 mt-5"><Button variant="secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>Trước</Button><span>Trang {page} / {Math.ceil(data.total / data.limit)}</span><Button variant="secondary" disabled={page * data.limit >= data.total} onClick={() => setPage(page + 1)}>Tiếp</Button></div>; }
export function Empty({ children }: { children: ReactNode }) { return <Card><p className="text-text-secondary">{children}</p></Card>; }
export function Back({ to, children = '← Quay lại' }: { to: string; children?: ReactNode }) { return <Link className="text-sm text-plum-noir underline" to={to}>{children}</Link>; }
export function statusError(error: unknown) { return error instanceof ApiError ? error.status : 0; }
