import { useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../api/endpoints';
import { ApiError } from '../../api/client';
import type { ReminderStatus } from '../../api/types';
import { Back, Button, Card, Empty, Notice, Pager, QueryState, Select, TextArea, Title, dateOnly, dateTime } from '../../app/ui';

const reminderLabel: Record<ReminderStatus, string> = { PENDING: 'Chờ đến hạn', DUE: 'Đến hạn', CONTACTED: 'Đã liên hệ', DISMISSED: 'Đã bỏ qua' };

function overdueDays(value: string) {
  const localDay = (date: Date) => { const parts = Object.fromEntries(new Intl.DateTimeFormat('en-US', { timeZone: 'Asia/Ho_Chi_Minh', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(date).map(p => [p.type, p.value])); return `${parts.year}-${parts.month}-${parts.day}`; };
  const day = localDay(new Date(value));
  const today = localDay(new Date());
  return Math.max(0, Math.round((Date.parse(`${today}T00:00:00Z`) - Date.parse(`${day}T00:00:00Z`)) / 86400000));
}
export function AdminReminders() {
  const [page, setPage] = useState(1); const [due, setDue] = useState(true);
  const list = useQuery({ queryKey: ['admin', 'reminders', due, page], queryFn: ({ signal }) => api.admin.reminders(due, page, signal) });
  return <><Title>Cần nhắc chăm sóc</Title><div className="flex flex-wrap gap-2 mb-5"><Button variant={due ? 'primary' : 'secondary'} onClick={() => { setDue(true); setPage(1); }}>Đến hạn chưa xử lý</Button><Button variant={!due ? 'primary' : 'secondary'} onClick={() => { setDue(false); setPage(1); }}>Tất cả</Button></div><QueryState loading={list.isLoading} error={list.error} retry={() => void list.refetch()}>{list.data?.items.length ? <div className="border border-border-custom rounded-panel bg-surface overflow-hidden"><table className="w-full text-sm"><thead className="hidden md:table-header-group bg-muted-surface/60 text-left text-text-secondary"><tr><th className="px-4 py-3 font-medium">Khách hàng</th><th className="px-4 py-3 font-medium">Thú cưng / dịch vụ</th><th className="px-4 py-3 font-medium">Ngày cần nhắc</th><th className="px-4 py-3 font-medium">Trạng thái</th></tr></thead><tbody className="divide-y divide-border-custom">{list.data.items.map(item => <tr key={item.id} className="block md:table-row p-4 md:p-0 hover:bg-canvas"><td className="block md:table-cell md:px-4 md:py-3"><Link to={`/admin/reminders/${item.id}`} className="font-semibold text-plum-noir underline underline-offset-4">{item.customer?.fullName || item.customerId}</Link><span className="block text-text-secondary">{item.customer?.phone || ''}</span></td><td className="block md:table-cell md:px-4 md:py-3 mt-1 md:mt-0">{item.pet?.name || item.petId}<span className="block text-text-secondary">{item.service?.serviceName || item.serviceId}</span></td><td className="block md:table-cell md:px-4 md:py-3 mt-1 md:mt-0">{dateOnly(item.reminderDate)}<span className="block text-text-secondary">Hoàn thành {dateOnly(item.completedDate)} · Quá hạn {overdueDays(item.reminderDate)} ngày</span></td><td className="block md:table-cell md:px-4 md:py-3 mt-1 md:mt-0 text-plum-noir">{reminderLabel[item.status]}</td></tr>)}</tbody></table></div> : <Empty>{due ? 'Không có khách cần nhắc.' : 'Chưa có reminder.'}</Empty>}<Pager page={page} setPage={setPage} data={list.data} /></QueryState></>;
}

export function AdminReminderDetail() {
  const { reminderId = '' } = useParams(); const client = useQueryClient(); const navigate = useNavigate();
  const [method, setMethod] = useState<'PHONE' | 'ZALO' | 'OTHER'>('PHONE'); const [note, setNote] = useState(''); const [error, setError] = useState<unknown>(); const [pending, setPending] = useState(false);
  const detail = useQuery({ queryKey: ['admin', 'reminder', reminderId], queryFn: ({ signal }) => api.admin.reminder(reminderId, signal), enabled: !!reminderId });
  const contact = async (event: FormEvent) => { event.preventDefault(); if (!window.confirm('Bạn đã liên hệ thực tế với khách hàng?')) return; setPending(true); setError(undefined); try { await api.admin.contact(reminderId, { method, ...(note.trim() ? { note: note.trim() } : {}) }); await client.invalidateQueries({ queryKey: ['admin', 'reminders'] }); await client.invalidateQueries({ queryKey: ['admin', 'reminder', reminderId] }); await client.invalidateQueries({ queryKey: ['admin', 'dashboard'] }); await client.invalidateQueries({ queryKey: ['admin', 'customers'] }); await client.invalidateQueries({ queryKey: ['admin', 'customer'] }); navigate('/admin/reminders'); } catch (e) { setError(e); if (e instanceof ApiError && e.status === 409) await detail.refetch(); } finally { setPending(false); } };
  const r = detail.data;
  return <><Back to="/admin/reminders" /><Title>Nhắc chăm sóc #{reminderId}</Title><QueryState loading={detail.isLoading} error={detail.error} retry={() => void detail.refetch()}>{r && <div className="grid lg:grid-cols-[minmax(0,1fr)_minmax(280px,360px)] gap-6 items-start"><Card className="space-y-2"><Notice error={error} /><p><b>Trạng thái:</b> {reminderLabel[r.status]}</p><p><b>Khách:</b> {r.customer?.fullName || r.customerId} · {r.customer?.phone}</p><p><b>Thú cưng:</b> {r.pet?.name}</p><p><b>Dịch vụ:</b> {r.service?.serviceName}</p><p><b>Hoàn thành:</b> {dateTime(r.completedDate)}</p><p><b>Ngày cần nhắc:</b> {dateOnly(r.reminderDate)}</p><p><b>Lịch hẹn nguồn:</b> <Link className="underline" to={`/admin/bookings/${r.bookingId}`}>#{r.bookingId}</Link></p><p><b>Giá gốc:</b> {r.booking?.services?.[0]?.basePrice ?? '—'} VND</p>{r.booking?.surcharges?.map(s => <p key={s.id}>Phụ phí {s.surchargeName}: {s.amount} VND</p>)}<p><b>Ghi chú:</b> {r.note || '—'}</p></Card><div className="space-y-5"><Card><h2 className="font-serif text-lg font-semibold mb-3">Lịch sử liên quan</h2>{r.pet?.activities?.length ? r.pet.activities.map(a => <p key={a.id} className="border-t border-border-custom py-2 text-sm">{dateTime(a.createdAt)} · {a.type} · {a.content || '—'}</p>) : <p>Chưa có hoạt động.</p>}</Card>{(r.status === 'PENDING' || r.status === 'DUE') && <Card><h2 className="font-serif text-lg font-semibold mb-3">Ghi nhận đã liên hệ</h2><form onSubmit={contact} className="space-y-3"><Select label="Phương thức" value={method} onChange={e => setMethod(e.target.value as 'PHONE' | 'ZALO' | 'OTHER')} options={[{ value: 'PHONE', label: 'Gọi điện' }, { value: 'ZALO', label: 'Zalo' }, { value: 'OTHER', label: 'Khác' }]} /><TextArea label="Ghi chú (tùy chọn)" value={note} onChange={e => setNote(e.target.value)} /><Button type="submit" disabled={pending}>{pending ? 'Đang lưu…' : 'Đã liên hệ'}</Button></form></Card>}</div></div>}</QueryState></>;
}
